"""add_github_token

Revision ID: 1b49abb5fe87
Revises: d4a7b1c2e9f0
Create Date: 2026-07-03 13:46:59.357731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b49abb5fe87"
down_revision: str | None = "d4a7b1c2e9f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("developers", sa.Column("github_token", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("developers", "github_token")
    # ### end Alembic commands ###
